name: CI - Build push da imagem docker
run-name: Executando CI - Build push da imagem docker - ${{ github.run_number }}
on:
  workflow_dispatch:

env:
  repositorio_nome_imagem: "magnocarlos1988/docker_pagina_php_hostname"

jobs:
  CI:
    runs-on: ubuntu-latest
    outputs:
      tag-image: ${{ steps.meta.outputs.SHORT_SHA }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.repositorio_nome_imagem }}:${{ steps.meta.outputs.SHORT_SHA }}
            ${{ env.repositorio_nome_imagem }}:latest
      
      - name: Docker Scout
        id: docker-scout-environment
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations
          image: "${{ env.repositorio_nome_imagem }}:${{ steps.meta.outputs.SHORT_SHA }}"
          organization: ${{ vars.DOCKERHUB_USERNAME }}